
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Divergency</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Remove="Content\Tiles\LivingGrove\CoreTreeCrystals.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Common\Players\DivergencyPlayer.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Content\Effects\SwordTrailShader\Testing.fx" />
    <None Remove="Content\Items\Weapons\LivingCore\CoreBarrageProj.png" />
    <None Remove="Content\NPCs\LivingGrove\CoreBlockadeRight.png" />
    <None Remove="Content\NPCs\LivingGrove\CorennectorProj.png" />
    <None Remove="Content\NPCs\LivingGrove\MarkscoreArrowHoming.png" />
    <None Remove="Content\NPCs\LivingGrove\MarkscoreArrowOrb.png" />
    <None Remove="Content\Projectiles\Hostile\BigGuy\LaserBeam.png" />
    <None Remove="Content\Projectiles\Melee\SacrifeBallThing.png" />
    <None Remove="TestStuff\Back_Body_Sheet.png" />
    <None Remove="TestStuff\Back_L_Legs_Sheet.png" />
    <None Remove="TestStuff\Back_R_Legs_Sheet.png" />
    <None Remove="TestStuff\Front_Body_Sheet.png" />
    <None Remove="TestStuff\Front_L_Legs_Sheet.png" />
    <None Remove="TestStuff\Front_R_Legs_Sheet.png" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\ParticleUtils\" />
    <Folder Include="Common\Systems\SkillNodes\ActiveSkills\" />
    <Folder Include="Common\Systems\SkillNodes\PassiveSkills\" />
    <Folder Include="Localization\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ParticleLibrary">
      <HintPath>Libraries\ParticleLibrary.dll</HintPath>
    </Reference>
    <Reference Include="SubworldLibrary">
      <HintPath>Libraries\SubworldLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>